### ISSUE TITLE
gcconnex: Please consider adding a "pronouns" box to the GCconnex basic profile

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcconnex#1386] opened 2017-09-05 17:45 UTC
Enhancement of existing feature
As a New User, I need Please consider adding a "pronouns" box to the GCconnex basic profile because To support trans and gender non-conforming members of the Public Service. Pronouns are what we use to respectfully refer to someone when not using their name, and so by giving people the option to have their pronouns listed on their profile it can allow people to show others how they wish to be referred to.

 - 9/5/2017 13:45:05

**Comment by klecuyer** [comment] 2017-09-05 17:50
Thank you for your contribution! This is a duplicate of #1356

**Closed by klecuyer** 2017-09-05 17:50 UTC
