### ISSUE TITLE
gcconnex: As a group owner, I need the ability to not send email notifications to all members after every small change.

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcconnex#1055] opened 2017-05-05 19:29 UTC
New Feature Request
As a Regular User, I need As a group owner, I need the ability to not send email notifications to all members after every small change. because As it is right now, the onus to control notifications is on the user. Very few people actually moderate their email notifications properly, and so they get frustrated when they receive an overload of emails from one group. Also, if owners had the option to send notifications or not, they could make changes and customize groups more freely, and could decide on a case-per-case basis, if the change would be of interest to all the group members.

samuel.burke@pco-bcp.gc.ca - 5/5/2017 15:29:26

**Comment by LemieuxGen** [comment] 2017-05-23 15:53
+1

**Comment by LemieuxGen** [comment] 2017-05-23 15:55
Could add the "Minor change" option to all content items (discussion comments, file versions, etc.)

**Comment by Troy-Lawson** [comment] 2017-05-23 19:01
Duplicate of gctools-outilsgc/gcconnex#1052

**Closed by Troy-Lawson** 2017-05-23 19:01 UTC
Labels: enhancement, High Priority, Notifications
