### ISSUE TITLE
BUG - polling functionality doesn't accurately record all votes. 

### ISSUE THREAD

**Issue by Eldoraaoun** [gctools-outilsgc/gcconnex#1363] opened 2017-08-24 15:34 UTC
Voting for Option A in this [poll](https://gcconnex.gc.ca/polls/view/29629880/enwhat-would-you-call-an-online-inventory-of-former-students-eligible-for-integration-in-the-federal-public-service-of-canadafrquel-nom-donneriez-vous-u00e0-un-ru00e9pertoire-en-ligne-danciens-u00e9tudiants-salariu00e9s-admissibles-u00e0-lu2019intu00e9gration-dans-la-fonction-publique-fu00e9du00e9rale-du-canada) is not recording. After having selected and saved the vote (and refreshing the page),  the results show 0 votes for Option A. 

Other users have mentioned encountering the same issue.

**Comment by Phanoix** [comment] 2017-08-30 14:05
Duplicate of #1355, which is just about fixed in #1373.

**Closed** 2017-08-30 17:29 UTC
