### ISSUE TITLE
"My Profile" sections broken

### ISSUE THREAD

**Issue by gabrielcossette-ca** [gctools-outilsgc/gcconnex#853] opened 2017-03-17 20:22 UTC
To reproduce:
1. Click on your name (top left) and **My Profile** button
2. Click on any of the following sections: Portfolio, Files, Blog, Wire posts, Badge Progress...
3. Nothing happens

Is this a wide issue or isolated to my profile? Weirdly, only the "Widgets" section works ;)

Thanks!

**Comment by ToferC** [comment] 2017-03-18 11:45
Thanks for sharing Gabriel. This doesn't seem to be site-wide. What browser and version are you using. Is this desktop or mobile?

**Comment by gabrielcossette-ca** [comment] 2017-03-20 14:07
You are right, it seems isolated to my profile. I tried to view another public profile and it worked.

Can you try to view my profile to see if it works on your side please? https://gcconnex.gc.ca/profile/gabrielcossette

And then select **Blog** for example, thanks!

**Comment by ToferC** [comment] 2017-03-20 20:50
@gabrielcossette-ca - confirmed.  The items are showing, but they are all down below your widgets.  It seems like there is a missing </div> in there somewhere.  Do you have an iframe in your widgets?  Can you try removing your widgets and see if things revert back to normal?

Otherwise confirming this as an issue.

**Comment by gabrielcossette** [comment] 2017-03-29 14:12
Hi!

Weird, I looked again this morning and the problem is now gone! You can close the issue.

Thanks Chris for the help!

**Closed** 2017-05-08 14:39 UTC
Labels: bug, Layout / CSS
