### ISSUE TITLE
GCconnex file permissions error

### ISSUE THREAD

**Issue by marc-donofrio** [gctools-outilsgc/gcconnex#2126] opened 2019-10-28 12:51 UTC
Access to the file is giving a permission error to admins and the file owner:

https://gcconnex.gc.ca/file/view/54308879/online-payments-in-sps-document-in-english-only-online-payments-in-sps?language=en

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Phanoix** [comment] 2019-11-05 16:04
related to #2075

**Comment by Phanoix** [comment] 2019-11-13 18:38
duplicate of #2075 and will be fixed when it is, closing.

**Closed by Phanoix** 2019-11-13 18:38 UTC
Labels: Duplicate, Project: Legacy Tools, [zube]: In Progress, bug
