### ISSUE TITLE
Gccollab digest not working

### ISSUE THREAD

**Issue by marc-donofrio** [gctools-outilsgc/gcconnex#2016] opened 2019-05-30 17:59 UTC
As a user of Gccollab, I need the daily digest to be notified of updates.

Several users are reporting that the digest emails are not being sent out. Resetting their notification options did not help.

Users who reported this issue:
alana.johnson@hrsdc-rhdcc.gc.ca
nick.schonning@cic.gc.ca
konstantinmanyakin@cmail.carleton.ca
chenaitukiso.muzondo@servicecanada.gc.ca
guillaume.faubert@canada.ca

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by nschonni** [comment] 2019-05-30 22:43
Duplicate of #2011 and #1975

**Comment by Phanoix** [comment] 2019-06-04 16:19
Looks like it's elgg cron issues, I'll set them up to be triggered through k8s jobs.

**Closed** 2019-06-13 13:43 UTC
Labels: Service: gccollab, [zube]: In Review, bug
