### ISSUE TITLE
gcconnex: There doesn't seem to be a way to prevent members in a group to make a blog post.  Is it possible to only allow group admins/operators the only ones that can post a file to the group, or post a blog post, etc.?

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcconnex#1163] opened 2017-06-16 15:07 UTC
New Feature Request
As a New User, I need There doesn't seem to be a way to prevent members in a group to make a blog post.  Is it possible to only allow group admins/operators the only ones that can post a file to the group, or post a blog post, etc.? because Some groups that I own will likely grow with 100+ users joining.  I don't want all users to be able make a blog post or upload a file.  I only want the admins to be able to do that.

sean.lam@canada.ca - 6/16/2017 11:07:05

**Comment by LemieuxGen** [comment] 2017-06-16 15:33
This is a duplicate of the issue #1039.

**Closed by LemieuxGen** 2017-06-16 15:33 UTC
Labels: duplicate
