### ISSUE TITLE
tagging someone in a GCcollab doesn't work

### ISSUE THREAD

**Issue by marc-donofrio** [gctools-outilsgc/gcconnex#2012] opened 2019-05-03 18:01 UTC
As a user of GCcollab group discussions, I need to tag users in order to notify them.

When typing @name and clicking on a username, the result is just the plain text username.

The following discussion was flagged as an example:
https://gccollab.ca/discussion/view/2169242/ensymposium-materialfr

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by piet0024** [comment] 2022-08-22 13:17
I was unable to reproduce this issue. I will close this for now and we can reopen this if we are getting more reports of this issue.

**Closed by piet0024** 2022-08-22 13:17 UTC
Labels: [zube]: Inbox, bug, Service: gccollab
