### ISSUE TITLE
Enhancement: Google Docs - Government Only

### ISSUE THREAD

**Issue by MishaGaudet** [gctools-outilsgc/gcconnex#1125] opened 2017-05-30 15:51 UTC
I've been talking to a couple of government employees and a lot wish to have a Google Docs but only for the government.

GCpedia is similar, but it doesn't have the "Live editing" feature.

I think it would really nice to have our own Google Docs and add it as a Tool.
https://docs.google.com/

**Comment by markwooff** [comment] 2017-05-30 15:57
This is actually something we've been looking at on the GCcollab side. There is an Open Source editor called Etherpad which allows you to edit documents collaboratively in real-time - can preview it on our dev site https://dev.gccollab.ca/pads

**Comment by gabrielcossette-ca** [comment] 2017-06-23 20:23
Sweet!

What's your estimated timeline for deployment on GCcollab production server?
And what about GCconnex?

Thanks!

CC: @smellems 

P.S.: duplicate of issue #222.

**Comment by markwooff** [comment] 2017-06-28 15:16
@gabrielcossette-ca not 100% sure at the moment as we're still looking at other Open Source software to provide document collaboration such as https://github.com/opengovfoundation/madison

Will definitely be letting users know if/when we release the new functionality.

**Comment by gabrielcossette-ca** [comment] 2017-06-28 15:44
@markwooff This Madison platform is for a different use case IMO.

- **Etherpad**: Brainstorming of ideas, cowriting of meeting minutes leading to a draft that is then exported and finalized elsewhere
- **Madison**: Get one way feedback in the form of comments and annotations

IMO we need both platforms badly :)

I'm asking about your plans because my management likes the Etherpad features and wish to have an internal GC instance. If this is a low priority right now, that's fine too, just wish to have the current state ;)

**Comment by markwooff** [comment] 2017-06-28 15:52
@gabrielcossette-ca agreed, but both are platforms we are putting exploratory work to see how they could integrate with GCcollab :)

At the moment, the main issue with Etherpad right now is performance. If we can find an optimal way to stand it up without affecting the overall performance of GCcollab then we may be able to launch it onto prod in a few weeks (best-case scenario).

**Comment by gabrielcossette-ca** [comment] 2017-06-28 16:13
@markwooff Performance? Is it because you are running it on the same server as GCcollab?

It's recommended to have a different server but the Etherpad platform is not very resource hungry from what I know.

**Comment by markwooff** [comment] 2017-06-28 16:41
It's on the same server for our dev box, but it'll be decoupled once moving to prod.

**Comment by gabrielcossette-ca** [comment] 2017-06-28 18:35
So there should be no performance effect on GCcollab.

And are there plans to add this feature to GCconnex too?

**Comment by markwooff** [comment] 2017-06-30 19:20
Unsure at the moment, but there is an issue for it here: https://github.com/gctools-outilsgc/gcconnex/issues/222

**Comment by markwooff** [comment] 2017-07-27 18:32
@gabrielcossette-ca just so you know, Etherpad is now live and running on GCcollab 👍
 https://gccollab.ca/docs/

**Comment by gabrielcossette-ca** [comment] 2017-07-27 20:40
Awesome news! Great job :)

Suggestions:
1. Is there a full screen button available? If so, you should enable it. The windows can be a bit small.
2. IMO, you should disable **Chat always on screen** and **Line numbers** settings by default.

**Comment by gabrielcossette-ca** [comment] 2017-07-27 20:41
Another suggestion. Could you pass the username to the Etherpad embedded instance so we don't have to write our name again?

**Comment by markwooff** [comment] 2017-07-28 15:10
Hi @gabrielcossette-ca, thanks for the feedback. There is a full screen button available but I had disabled it for launch. It'll most likely be back in next week. I've set the **Chat always on screen** and **Line numbers** options to be off by default. Users can always override these settings individually.

And yes that's actually something I've been working on for the last 24 hours. A user's name will be passed into the Etherpad instance now. Cheers!

**Comment by gabrielcossette-ca** [comment] 2017-08-01 14:16
Super :)

**Chat always on screen** is still checked by default on my side... It seems you also need to disable **Show Chat and Users** to be able to uncheck it. Let me know if I can help testing.

**Comment by markwooff** [comment] 2017-08-02 14:55
Looks like you're right, had to set both options to `false` - this has now been done. However, we're leaving the **Line numbers** option to default to `true` because this left-hand sidebar also shows the usernames of user's who have made changes to the Doc.

**Comment by gabrielcossette-ca** [comment] 2017-08-02 15:39
Great, working now. Let us know when you've added the full screen button so we can test.

**Comment by marc-donofrio** [comment] 2020-08-13 18:22
Etherpad shut down. New enhancements on hold due to maintenance mode.

**Closed by marc-donofrio** 2020-08-13 18:22 UTC
Labels: Project: Legacy Tools, [zube]: Inbox
