### ISSUE TITLE
Notification Duplicates- 4x notifications for each update

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/gcconnex#1267] opened 2017-07-18 15:34 UTC
Submitted on behalf of username: powerc

As a user, I am receiving 4x notifications for each update in a group, the Social Media Community of Practice specifically. It is not just the owner making multiple modifications to a post within the same minute, but exactly identical notifications I am receiving four times for each post. 

I have check the user's notification settings in the Admin panel and is subscribed only one time to each subscription.
![image](https://user-images.githubusercontent.com/29754185/28325866-fff26f10-6bac-11e7-9da4-993d174b95f6.png)

Link to user's notifications: https://gcconnex.gc.ca/messages/notifications/powerc

**Comment by pandurx** [comment] 2017-07-18 15:47
please see issue #1070  for update

**Comment by Phanoix** [comment] 2017-07-18 19:13
Duplicate of #1070.

**Closed by Phanoix** 2017-07-18 19:13 UTC
Labels: bug, duplicate
