### ISSUE TITLE
GCconnex search not coming up with any results when searching for existing users

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#471] opened 2016-11-15 17:20 UTC
When searching for an existing user in the GCconnex federated search (GSA), the user's profile doesn't not show up in the search results. This was replicated on multiple occasions, with new users and existing users. Example: Nicolas Carpentier is an existing user, he has a profile page (https://gcconnex.gc.ca/profile/Nicolas.Carpentier), but his profile doesn't come up in search results, and also doesn't appear in the list of members (https://gcconnex.gc.ca/members/gc_dept?dept=SSC-SPC&sort=alpha&order=ASC&offset=300#). 
![capture_nicolas carpatier](https://cloud.githubusercontent.com/assets/15378977/20315816/5142c20c-ab2d-11e6-8622-1d8dd5bfb7ad.JPG)
![capture_nicolas carpentier_members list](https://cloud.githubusercontent.com/assets/15378977/20315827/5de85954-ab2d-11e6-8c46-d208ffca6cca.JPG)

This issue was replicated with these users: 
•	Yugin Wong (new user - account created Nov 15)
•	Karine Maisonneuve-Mongeon (account created some time ago)

**Comment by LemieuxGen** [comment] 2016-11-17 15:04
@cdegrass The fact that the users are not showing up in the list of members if troubling... would this mean that the issue may not be related to the GSA indexing?

**Comment by ToferC** [comment] 2016-12-01 18:04
@cdegrass @pandurx - please track the current work on the GSA indexing on this issue.  Thanks!

**Comment by ToferC** [comment] 2016-12-01 18:08
New feedback from Rajeev:

3.	Is GSA unable to index new documents in a timely manner? – Absolutely not if there is enough licensing capacity but the GSA has once again reached its max. licensing limit.   As I have said it before, the **GSA crawler is going into a loop due to the way GCconnex hyperlinks are coded**.  Once the GCconnex team fixes this issue, GSA will resume indexing.

**Comment by ToferC** [comment] 2016-12-13 14:05
@cdegrass @pandurx @Troy-Lawson - Hello all.  We discussed this in the sprint planning session yesterday, but I want to flag that this issue's resolution is critical.  We say that GCconnex is about connecting our people to each other and the knowledge they need to do their work.  This doesn't fly if basic search for new members doesn't work.

**Comment by pandurx** [comment] 2016-12-13 16:08
Is this still recurring? I informed Rajeev of the implementation to production over the weekend, and he said he would re-crawl the site on Sunday.

**Comment by Troy-Lawson** [comment] 2016-12-13 16:26
how often is the crawl?

**Comment by pandurx** [comment] 2016-12-13 16:27
depends how much content is on the site

**Comment by Troy-Lawson** [comment] 2016-12-13 16:30
Search for a user who joined around 2 pm yesterday (dec 12th) Emmanuelle Seguin doesnt show up. Is this expected behaviour?

**Comment by pandurx** [comment] 2016-12-13 16:36
Can they be found in the Members section? (I remember Gen bringing up the fact that some users are not in the Member list)

They should be present in GSA search by now.

**Comment by Troy-Lawson** [comment] 2016-12-13 16:38
Yes i had picked the user from the member list. Around page 8. Just picked one as a random test

**Comment by Troy-Lawson** [comment] 2016-12-15 21:47
@pandurx any update since Rajeev's email? can we close?

**Comment by pandurx** [comment] 2016-12-16 02:15
This is something that could be ongoing (maintaining search functionality). It could be fixed now but later down the line, something could happen and break it.
I think this can be closed.

**Comment by ToferC** [comment] 2016-12-16 13:55
Can we build a test for this?

**Comment by pandurx** [comment] 2016-12-16 18:58
test script to test periodically?

**Comment by pandurx** [comment] 2016-12-21 13:42
Currently, the GSA indexing the same page over and over again has come up again, because it is ignoring my check somehow... (see pull request Github#630 for patch) and now it has run out of space for more documents for new things.

**Comment by KevinChagnon** [comment] 2017-02-08 20:17
This issue is ongoing. user **Francine.Chretien** cannot be found using Search
![francine chretien](https://cloud.githubusercontent.com/assets/23527358/22755527/825a8b50-ee11-11e6-9029-9c656dc3f95a.JPG)
![francine chretien](https://cloud.githubusercontent.com/assets/23527358/22755533/89f70672-ee11-11e6-9ec3-28445e98c269.JPG)

but user does have an active profile: https://gcconnex.gc.ca/profile/Francine.Chrétien

![francine chretien profile](https://cloud.githubusercontent.com/assets/23527358/22755577/c1c1f4fe-ee11-11e6-92a3-e6c470cc010f.JPG)

**Comment by KevinChagnon** [comment] 2017-02-08 20:22
Additionally, the user Francine.Chretien also does not show up in Cometchat for other users although she is logged in and setting are set to "Disponible"

**Comment by ToferC** [comment] 2017-02-08 23:53
Comet chat currently has limited functionality due to server performance
issues. We're looking at options. @cdegrass

**Comment by pandurx** [comment] 2017-04-24 18:07
Francine Chretien comes up in the results, the title for the results had been resolved awhile ago as well.
@KevinChagnon  is this still an issue?

**Closed** 2017-04-25 14:31 UTC
Labels: bug, Project plan deliverable, Usability
