### ISSUE TITLE
gcconnex: Please consider adding a "pronouns" box to the GCconnex basic profile.

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcconnex#1385] opened 2017-09-05 12:38 UTC
Enhancement of existing feature
As a Regular User, I need Please consider adding a "pronouns" box to the GCconnex basic profile. because To support trans and gender non-conforming members of the Public Service. Pronouns are what we use to respectfully refer to someone when not using their name, and so by giving people the option to have their pronouns listed on their profile it can allow people to show others how they wish to be referred to.

 - 9/5/2017 8:38:48

**Comment by klecuyer** [comment] 2017-09-05 15:33
Hello and thank you for your feedback. This is an existing enhancement request in Github: https://github.com/gctools-outilsgc/gcconnex/issues/1356 here you can track any progress on this ticket, as well as link to the main discussion in GCconnex. Thank you for your contribution!

**Comment by klecuyer** [comment] 2017-09-05 17:49
Duplicate of #1356

**Closed by klecuyer** 2017-09-05 17:49 UTC
Labels: Enhancement
