### ISSUE TITLE
Issue with lanague link "This content is also available in English"

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/gcconnex#769] opened 2017-02-02 14:51 UTC
When you look at a discussion, and use the link "This content is also available in English" OR "Ce contenu est aussi disponible en français", the comments in the discussion change to show the initial discussion post. (This happens in both English and French).
Example: https://gcconnex.gc.ca/discussion/view/24574031/have-your-say-help-us-improve-gcintranet

Initial post with discussion (BEFORE using the language split link.
![language split link_1](https://cloud.githubusercontent.com/assets/15378977/22553806/05bae64c-e92c-11e6-9e67-684338e01099.JPG)

AFTER clicking on the language split link to see the FRENCH content "Cette discussion est aussi disponible en Francais"
![language split link_2](https://cloud.githubusercontent.com/assets/15378977/22554122/0aa2efa0-e92d-11e6-962a-d432d74e009e.JPG)

AFTER clicking on the language split link to see the ENGLISH content "This content is also available in English"
![language split link_3](https://cloud.githubusercontent.com/assets/15378977/22554131/122a5c2c-e92d-11e6-8b93-45ef5ee46197.JPG)

**Comment by ToferC** [comment] 2017-02-02 14:55
This bug is a duplicate of #723 - please keep for additional context and close with that issue.  Assigned to @Steph4104 @LemieuxGen

**Closed** 2017-02-02 15:01 UTC
Labels: bug, High Priority
