### ISSUE TITLE
gcconnex: A better onboarding tool or pop up that assists users in better managing their notification settings as soon as they join GCConnex or a groups on they have joined.

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcconnex#892] opened 2017-03-30 13:37 UTC
Enhancement of existing feature
As a Regular User, I need A better onboarding tool or pop up that assists users in better managing their notification settings as soon as they join GCConnex or a groups on they have joined. because Notifications are sent to every group member (who hasn’t yet adjusted their settings) every time someone makes an edit or creates a folder in a group. Since most people don’t immediately edit their notification and email settings, this creates a lot of white noise in users’ email inboxes and GC notifications, even possibly resulting in people leaving your group if they do not understand they can change it. This can discourage people from joining or staying in a group, especially if the owner is particularly involved, creating the opposite effect

 - 3/30/2017 9:37:20

**Comment by Phanoix** [comment] 2017-03-30 14:54
Duplicate of #652

**Closed by Phanoix** 2017-03-30 14:54 UTC
Labels: duplicate
