### ISSUE TITLE
gcconnex: You know the function that displays 4 colleagues that you may potential know and asks if you want to connect with them. There should be an option (like Facebook or LinkedIn) that allows you to swipe/scroll through suggested colleagues or click an x at the top of their profile box and have it be replaced with another suggested colleague

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcconnex#1159] opened 2017-06-16 13:55 UTC
Enhancement of existing feature
As a Super User, I need You know the function that displays 4 colleagues that you may potential know and asks if you want to connect with them. There should be an option (like Facebook or LinkedIn) that allows you to swipe/scroll through suggested colleagues or click an x at the top of their profile box and have it be replaced with another suggested colleague because This will follow along with the Facebook/LinkedIn platform and allow users to add more colleagues through suggested users than only have the option of seeing 4 

erin.chapman@tbs-sct.gc.ca - 6/16/2017 9:55:33

**Comment by ToferC** [comment] 2017-06-30 20:20
Closing as duplicate of gctools-outilsgc/gcconnex#418 .

**Closed by ToferC** 2017-06-30 20:20 UTC
