### ISSUE TITLE
Work Experience: Ability to add work experience anywhwere in list of prior entries

### ISSUE THREAD

**Issue by KevinChagnon** [gctools-outilsgc/gcconnex#674] opened 2017-01-12 17:53 UTC
When adding a new Work Experience in a user profile, it adds it to the end. 
Work Experience should be sorted in reverse chronological order - that is, so that the most recent work experience is at the top.

Request: Ability for a user to add a new Work experience anywhere within the list of prior entries including top and bottom of the list.

**Comment by KevinChagnon** [comment] 2017-01-25 21:22
+1

**Comment by ToferC** [comment] 2017-02-09 15:23
Duplicate of #774 which has more context.  Closing issue.

**Closed by ToferC** 2017-02-09 15:23 UTC
Labels: enhancement
