### ISSUE TITLE
gcconnex: Please consider adding a "pronouns" box to the GCconnex basic profile

### ISSUE THREAD

**Issue by GCToolsEnhancement** [gctools-outilsgc/gcconnex#1383] opened 2017-09-05 12:34 UTC
Enhancement of existing feature
As a Regular User, I need Please consider adding a "pronouns" box to the GCconnex basic profile because To support trans and gender non-conforming members of the Public Service. Pronouns are what we use to respectfully refer to someone when not using their name, and so by giving people the option to have their pronouns listed on their profile it can allow people to show others how they wish to be referred to.

Mathieu.Mazur-Goulet@canada.ca - 9/5/2017 8:34:29

**Comment by klecuyer** [comment] 2017-09-05 17:49
Duplicate of #1356

**Closed by klecuyer** 2017-09-05 17:49 UTC
Labels: Enhancement
