### ISSUE TITLE
File button error -- GCcollab

### ISSUE THREAD

**Issue by Menrika** [gctools-outilsgc/gcconnex#2625] opened 2023-10-24 18:03 UTC
## Radio buttons are not working and return an error message when clicked: javascript:void(0); - see attached image, error message in lower left of page when hovering over "select all" radio button.

When clicking on "New file folder" button in the parent folder where the new folder should be placed, the page returns me to the main folder page so I am unable to create new folders. Unable to capture a screen recording of this but happy to connect via teams to demo what happens.

## Details on issue or enhancement
![image](https://github.com/gctools-outilsgc/gcconnex/assets/45214337/e9a71e8d-0fcc-45ea-a3dc-725665743239)

Group : https://gccollab.ca/file/group/3603354/all#

Cant replicate this error 

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by Phanoix** [comment] 2023-10-24 20:15
duplicate of #2609 and should be fixed now.

**Closed by Phanoix** 2023-10-24 20:15 UTC
Labels: Service: gccollab, Duplicate
