### ISSUE TITLE
Submit a ticket issue

### ISSUE THREAD

**Issue by Menrika** [gctools-outilsgc/gcconnex#2493] opened 2023-02-22 15:34 UTC
## error when submitting a ticket on GCconnex

![image](https://user-images.githubusercontent.com/45214337/220671294-9b1189e2-9bb2-4938-b149-7ce46b01a091.png)

**Browser console** 

![image](https://user-images.githubusercontent.com/45214337/220671772-51e4ba92-218b-40c5-bcc2-d8b11800b9ca.png)

 
![image](https://user-images.githubusercontent.com/45214337/220671696-d43cc4d5-44c6-4d07-9d7b-74d3b07b471c.png)

 

## Details on issue or enhancement

User email with SSC

inactive account

https://support.gccollab.ca/a/tickets/27811 

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by piet0024** [comment] 2023-03-09 20:34
I believe this is a duplicate of this issue: https://github.com/gctools-outilsgc/gcconnex/issues/2488
Closing this issue because of duplication.

**Closed by piet0024** 2023-03-09 20:34 UTC
Labels: Project: Legacy Tools, Freshdesk, Duplicate
