### ISSUE TITLE
multi post messages when someone puts something new on GCconnex

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/gcconnex#322] opened 2016-10-28 19:41 UTC
GCCON-178
From: Marc.Turcotte@nserc-crsng.gc.ca 
 Just now I just got 7 emails because someone posted a new item to one of the groups I follow. 
 
 The link in for one of the emails is this: https://gcconnex.gc.ca/messages/read/21393536

**Comment by Phanoix** [comment] 2016-11-17 16:36
Do the items also end up posted multiple times and/or appear multiple times under activity?

**Comment by pandurx** [comment] 2016-11-17 19:44
It does.. most of the time (with different users)

**Comment by Phanoix** [comment] 2016-11-17 19:48
So the rest of it (multiple notifications, activity entries) is working as intended considering the content ends up created multiple times, and we just need to prevent that from happening... I'll check if anything has been done recently regarding this in the newer elgg version.

**Comment by Phanoix** [comment] 2016-11-18 18:42
Confirmed to occur as a result of database load spikes / long table locks.

**Comment by sboots** [comment] 2017-01-18 14:46
Hey team! Quick note that I'm also seeing this behaviour when posts are made, or bookmarks are added, to large groups (1000+ members). 

Typical steps to replicate are,
1. find a large group (eg. https://gcconnex.gc.ca/bookmarks/group/18885366/all)
2. add a new bookmark
3. after clicking "Add a bookmark" on the form to save it, the browser will stall while waiting to load the page
4. depending on the browser, it may try to re-submit the form automatically, causing several duplicate posts to appear.

One possibility is that this is related to the email notifications that are sent out to every member of the group (if they're done synchronously with the page load rather than asynchronously in some other process). That might explain why this is only an issue with really large groups.

Thanks and rock on! 

![gcconnex-multi-post-20170118](https://cloud.githubusercontent.com/assets/263472/22068419/f69e2cb6-dd62-11e6-8cb8-d212cee4c829.png)

**Comment by ToferC** [comment] 2017-01-18 14:56
This is super useful context @sboots - thanks!

**Comment by pandurx** [comment] 2017-01-19 03:05
See tbs-sct/gcconnex#351

**Comment by Troy-Lawson** [comment] 2017-02-13 19:39
same as gctools-outilsgc/gcconnex#351

**Comment by ToferC** [comment] 2017-06-30 19:05
Closing as issue addressed by @Phanoix .

**Closed by ToferC** 2017-06-30 19:05 UTC
Labels: bug, Optimization
